name: Feedback
description: Provide feedback on the Ubuntu Server documentation.
title: "[Feedback]: "
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this feedback!**
        We really appreciate your input, and it will help us improve the documentation.
        
        Please provide an appropriate title, usually found at the top of the page.
        
        ---
  - type: input
    id: page_url
    attributes:
      label: Page URL
      description: Please enter the URL of the page you are referring to.
      type: url
    validations:
      required: true
  - type: checkboxes
    id: content
    attributes:
      label: Select an option
      description: Please let us know what issue you encountered with the documentation.
      options:
        - label: I found what I was looking for
          required: false
        - label: I couldn't find what I was looking for
          required: false
        - label: I found the information, but it was incorrect
          required: false
        - label: I found the information, but it was incomplete
          required: false
        - label: I found the information, but it was confusing
          required: false
        - label: I encountered a technical issue (e.g., broken link, image not loading)
          required: false
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: |
        Please provide a detailed description of the issue:
        - What part of the documentation were you trying to use?
        - What did you expect to happen, and what actually happened?
        - Any error messages or screenshots you can provide would be very helpful.
    validations:
      required: true
      